/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
class XrossPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can build rust and generate kotlin code`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('org.example.xross-plugin')
            }
            tasks.named("build") {
                dependsOn("buildRust")
                dependsOn("generateXrossKotlin") // Assume this task will be added later
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("build") // Run the build task to trigger buildRust and generateXrossKotlin
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify that buildRust task ran successfully
        assertTrue(result.output.contains("Building xross-core for target"))
        val metadataFile = projectDir.resolve("build/rust/xross_metadata.json")
        assertTrue(metadataFile.exists(), "xross_metadata.json should be generated")

        // Verify that Kotlin files are generated (assuming MyStruct and InnerStruct are used)
        val generatedKotlinDir = projectDir.resolve("build/generated/xross/src/main/kotlin/org/example/xross")
        assertTrue(generatedKotlinDir.exists(), "Generated Kotlin directory should exist")
        assertTrue(generatedKotlinDir.resolve("MyStruct.kt").exists(), "MyStruct.kt should be generated")
        assertTrue(generatedKotlinDir.resolve("InnerStruct.kt").exists(), "InnerStruct.kt should be generated")

        // Create a simple Kotlin application to use the generated code
        val appKotlinSource = generatedKotlinDir.resolve("App.kt") // App.kt は生成される
        appKotlinSource.parentFile.mkdirs()
        appKotlinSource.writeText("""
            package org.example.xross

            fun main() {
                // Assuming MyStruct is generated
                val myStruct = MyStruct.new()
                myStruct.value = 123U // Assuming 'value' field is generated
                println("MyStruct value: ${myStruct.value}")
                // Add more calls to generated methods/properties for full testing
                myStruct.close()
            }
        """.trimIndent())

        buildFile.appendText("""
            application {
                mainClass.set("org.example.xross.AppKt")
            }
        """.trimIndent())

        // Run the application
        val appRunner = GradleRunner.create()
        appRunner.forwardOutput()
        appRunner.withPluginClasspath()
        appRunner.withArguments("run") // Run the application
        appRunner.withProjectDir(projectDir)
        val appResult = appRunner.build()

        assertTrue(appResult.output.contains("MyStruct value: 123"), "Generated Kotlin code should execute and interact with Rust FFI.")

    }
}
