/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xross

import org.gradle.api.Project
import org.gradle.api.Plugin

class XrossPluginPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'org.example.greeting'")
            }
        }
    }
}
